#!/bin/sh

BIN_DIR=/usr/local/bin
ADDON_DIR=/usr/local/etc/config/addons/pmatic
RCD_DIR=/usr/local/etc/config/rc.d
CONFIG_DIR=/usr/local/etc/config

if [ "$1" = "" ]; then
  echo "CCU1"
  lcdtool "installing pmatic   "
  mount -t yaffs /dev/mtdblock3 /usr/local
elif [ "$1" = "CCU2" ]; then
  echo "CCU2"
  if ! mount | grep ^ubi1:user.*rw >/dev/null 2>&1; then
      mount -t ubifs ubi1:user /usr/local
  fi
elif [ "$1" = "HM-RASPBERRYMATIC" ]; then
  echo "HM-RASPBERRYMATIC"
  mount /usr/local
fi

# remove files of old versions (same as in pmatic.init)
rm /usr/local/bin/python2.7 /usr/local/bin/python
rm -rf $ADDON_DIR

mkdir -p $ADDON_DIR $RCD_DIR
chmod 755 $ADDON_DIR $RCD_DIR

# Make python executable shipped with pmatic available via PATH
ln -s ../etc/config/addons/pmatic/python/bin/python2.7 $BIN_DIR/python2.7
cp python-wrapper $BIN_DIR/python
chmod +x $BIN_DIR/python

# copy all stuff and setup rc.d
cp -R examples python $ADDON_DIR/
cp -R pmatic $ADDON_DIR/python/lib/python2.7/
ln -s python/lib/python2.7/pmatic $ADDON_DIR/pmatic
cp pmatic.init $RCD_DIR/pmatic
chmod +x $RCD_DIR/pmatic

sync

if [ "$1" = "" ]; then
  echo "CCU1"
  lcdtool "Reboot...             "
  lcdtool -a 0x40 -t bin 00
  echo "x" > /dev/watchdog
  reboot
  while true ; do true ;  done
elif [ "$1" = "CCU2" ]; then
  echo "CCU2"
  # CCU2 always reboots after Addon/Firmware Update
elif [ "$1" = "HM-RASPBERRYMATIC" ]; then
  echo "HM-RASPBERRYMATIC"
  # RASPBERRYMATIC always reboots after Addon/Firmware Update
fi
